name: Kwiki-Widgets-RandomQuote
version: 0.01
abstract: Quote a random paragraph from wiki pages.
author: Kang-min Liu <gugod@gugod.org>
license: perl
distribution_type: module
build_requires:
  Test::More: 0
requires:
  Kwiki: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.37
